### ISSUE TITLE
No handle for users with no profile picutre

### ISSUE THREAD

**Issue by JEF1056** [thec0sm0s/Flask-Discord#14]
Exactly as explained; here's an example traceback
```Traceback (most recent call last):
  File "/home/admins/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admins/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admins/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/admins/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/admins/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admins/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/admins/.local/lib/python3.6/site-packages/flask_discord/utils.py", line 22, in wrapper
    return view(*args, **kwargs)
  File "website.py", line 121, in data
    return render_template("data.html", avatar_url=str(user.avatar_url)+"?size=512", user=user, guilds=guilds_data, num_guilds=len(guilds_data), guild_settings=guild_settings)
  File "/home/admins/.local/lib/python3.6/site-packages/flask_discord/models/user.py", line 106, in avatar_url
    if self.is_avatar_animated else configs.DISCORD_IMAGE_FORMAT
  File "/home/admins/.local/lib/python3.6/site-packages/flask_discord/models/user.py", line 113, in is_avatar_animated
    return self.avatar_hash.startswith("a_")
AttributeError: 'NoneType' object has no attribute 'startswith'```

**Comment by thec0sm0s** [comment]
Thanks for poiting it out. Was fixed with commit: 1fc91d24c20e0488c8580a5886b715f9cd497d67 and updated PyPI. You may update the package and give it a try again.
