### ISSUE TITLE
KeyError: 'DISCORD_CLIENT_ID'

### ISSUE THREAD

**Issue by lucaytpols** [thec0sm0s/Flask-Discord#36]
```Traceback (most recent call last):
  File "c:\Users\Luite\Documents\PixelBot_dev\site\app.py", line 7, in <module>
    discord = DiscordOAuth2Session(app)
  File "C:\Users\Luite\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_discord\_http.py", line 42, in __init__
    self.init_app(app)
  File "C:\Users\Luite\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_discord\_http.py", line 54, in init_app
    self.client_id = self.client_id or app.config["DISCORD_CLIENT_ID"]
KeyError: 'DISCORD_CLIENT_ID'``` any idea?

**Comment by thec0sm0s** [comment]
Looks like you haven't set `DISCORD_CLIENT_ID` in your Flask app config. Do this or pass `client_id` to `DiscordOAuth2Session` when initializing it.

**Comment by lucaytpols** [comment]
Well i did.

![](https://cdn.discordapp.com/attachments/789071207353155634/791618723916152832/unknown.png)

**Comment by lucaytpols** [comment]
error fixed.
