### ISSUE TITLE
Error in models/guild.py

### ISSUE THREAD

**Issue by KittyLe** [thec0sm0s/Flask-Discord#7]
```
   File "/home/okame/bots/flex/cogs/http.py", line 93, in dboard
     for guild in self.discord.fetch_guilds():
   File "/home/okame/.local/lib/python3.8/site-packages/flask_discord/client.py", line 107, in fetch_guilds
     return [models.Guild(payload) for payload in guilds_payload]
   File "/home/okame/.local/lib/python3.8/site-packages/flask_discord/client.py", line 107, in <listcomp>
     return [models.Guild(payload) for payload in guilds_payload]
   File "/home/okame/.local/lib/python3.8/site-packages/flask_discord/models/guild.py", line 26, in __init__
     self.id = int(self._payload["id"])
TypeError: string indices must be integers
```

**Comment by thec0sm0s** [comment]
I tried myself and cannot reproduce the same error. Can you make sure you're using the latest version `0.1.10`?
Also, can you check what is returned in payload object in your case. Seems like it isn't returning the list of guilds.

**Comment by KittyLe** [comment]
> Seems like it isn't returning the list of guilds.
It does return full list of my servers even with their ids
```
...
{'id': '703204504828641340', 'name': 'Дистанционка', 'icon': None, 'owner': True, 'permissions': 2147483647, 'features': []}
global
[2020-04-28 07:19:03,721] ERROR in app: Exception on /dashboard/ [GET]
Traceback (most recent call last):
  File "/home/okame/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
```

**Comment by KittyLe** [comment]
It appears that doing this:
```py
for guild in self.discord.fetch_guilds():
                    print(guild)
```
Gives only guild names, not `dict`

**Comment by thec0sm0s** [comment]
`.fetch_guilds()` returns [`models.Guild`](https://flask-discord.readthedocs.io/en/latest/api.html#flask_discord.models.Guild) object. Using `print(guild)` will call the `__str__` method of this object which is name of this guild. To access any of the attributes of guilds, you can use `guild.name`, `guild.id`, `guild.icon_url`, ...

However, if you still want the actual payload returned from discord, you can use `guild.to_json()`.

**Comment by KittyLe** [comment]
```py
for guilb in self.client.guilds:
                for guild in self.discord.fetch_guilds():
                    if guilb.id == guild.id:
                       print("ok")
```
Tried this, still gives this error

**Comment by thec0sm0s** [comment]
May I know what your `self.client.guilds` property returns? Also the error your'e getting.

**Comment by KittyLe** [comment]
`self.client.guilds` returns everything that it should, I just checked. Error I'm getting is:
```py
[2020-04-28 11:47:42,663] ERROR in app: Exception on /dashboard/ [GET]
Traceback (most recent call last):
  File "/home/okame/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/okame/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/okame/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/okame/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/okame/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/okame/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/okame/bots/flex/cogs/http.py", line 93, in dboard
    for guild in self.discord.fetch_guilds():
  File "/home/okame/.local/lib/python3.8/site-packages/flask_discord/client.py", line 107, in fetch_guilds
    return [models.Guild(payload) for payload in guilds_payload]
  File "/home/okame/.local/lib/python3.8/site-packages/flask_discord/client.py", line 107, in <listcomp>
    return [models.Guild(payload) for payload in guilds_payload]
  File "/home/okame/.local/lib/python3.8/site-packages/flask_discord/models/guild.py", line 26, in __init__
    self.id = int(self._payload["id"])
TypeError: string indices must be integers
127.0.0.1 - - [28/Apr/2020 11:47:42] "GET /dashboard/ HTTP/1.0" 500 -
```

**Comment by OkameProductions** [comment]
Can replicate this issue locally.
```py
[2020-04-28 13:49:43,842] ERROR in app: Exception on /dashboard/ [GET]
Traceback (most recent call last):
  File "/home/okame/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/okame/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/okame/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/okame/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/okame/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/okame/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/okame/TeamFlex/Flex/cogs/http.py", line 93, in dboard
    for guild in self.discord.fetch_guilds():
  File "/home/okame/.local/lib/python3.8/site-packages/flask_discord/client.py", line 107, in fetch_guilds
    return [models.Guild(payload) for payload in guilds_payload]
  File "/home/okame/.local/lib/python3.8/site-packages/flask_discord/client.py", line 107, in <listcomp>
    return [models.Guild(payload) for payload in guilds_payload]
  File "/home/okame/.local/lib/python3.8/site-packages/flask_discord/models/guild.py", line 26, in __init__
    self.id = int(self._payload["id"])
TypeError: string indices must be integers
127.0.0.1 - - [28/Apr/2020 13:49:43] "GET /dashboard/ HTTP/1.1" 500 -
```

**Comment by OkameProductions** [comment]
**UPDATE**
After updating the dashboard page code, the issue is non-replicable in our current workflow.

**Comment by KittyLe** [comment]
Okay, thanks for help @thec0sm0s! Closing that issue

**Comment by thec0sm0s** [comment]
I am curious on what caused that to be raised. As if payload is just a string.

**Comment by OkameProductions** [comment]
The same thing happened to me before, but a reload fixed it. I think some of the code @KittyLe wrote caused flask-discord to chew up and break. He was comparing data from d.py to data from flask-discord after all.
